%PDF-1.4
%Çì¢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
xœu‘;oÃ …w~Åİê‡p¹~©K¤.U34Bêu°ğ#VıHìTj–şöbGNšÂ€€ïœs¹9l˜z•5yÜFPô„AAÇKĞ‹¬a-"'“! Š™ãyˆšìŒMò™åe•™Ô3Ş³6ÉX¹qÅ»}}æ‡xQ®+íê@1Ü\©²CnÒPIUq¨“²YeI3ÊA¼ÃåæÖÎğ4;`ì´°-›bı•çYç´£j }M‚…m-îI€¶S,¥ı)}’¶Í¾G#˜cÃE¬Óê`y8\Ò¢ûiT^£F<;®´`Y_–¥$Ëí^;ĞPuuãØ¿©7F´Êûº¢ı¹?eõßw"Îe¡«-Ç/àpy z7Yòér°Tÿ,§{°~&úY75DÍ endstream
endobj
6 0 obj
317
endobj
4 0 obj
<</Type/Page/MediaBox [0 0 595 842]
/Rotate 0/Parent 3 0 R
/Resources<</ProcSet[/PDF /Text]
/ExtGState 10 0 R
/Font 11 0 R
>>
/Contents 5 0 R
>>
endobj
3 0 obj
<< /Type /Pages /Kids [
4 0 R
] /Count 1
>>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Metadata 13 0 R
>>
endobj
7 0 obj
<</Type/ExtGState
/OPM 1>>endobj
10 0 obj
<</R7
7 0 R>>
endobj
11 0 obj
<</R9
9 0 R/R8
8 0 R>>
endobj
9 0 obj
<</BaseFont/Courier/Type/Font
/Encoding 12 0 R/Subtype/Type1>>
endobj
12 0 obj
<</Type/Encoding/Differences[
126/tilde]>>
endobj
8 0 obj
<</BaseFont/Courier-Bold/Type/Font
/Subtype/Type1>>
endobj
13 0 obj
<</Type/Metadata
/Subtype/XML/Length 1412>>stream
<?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CRLF"?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='uuid:a5b5bb83-0e16-11ef-0000-86267823bc43' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Producer='GPL Ghostscript 9.14'/>
<rdf:Description rdf:about='uuid:a5b5bb83-0e16-11ef-0000-86267823bc43' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2014-05-07T11:13:09-04:00</xmp:ModifyDate>
<xmp:CreateDate>2014-05-07T11:13:09-04:00</xmp:CreateDate>
<xmp:CreatorTool>GNU Enscript 1.6.6</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='uuid:a5b5bb83-0e16-11ef-0000-86267823bc43' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:a5b5bb83-0e16-11ef-0000-86267823bc43'/>
<rdf:Description rdf:about='uuid:a5b5bb83-0e16-11ef-0000-86267823bc43' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Enscript Output</rdf:li></rdf:Alt></dc:title><dc:creator><rdf:Seq><rdf:li></rdf:li></rdf:Seq></dc:creator></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
                                                                        
                                                                        
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.14)
/CreationDate(D:20140507111309-04'00')
/ModDate(D:20140507111309-04'00')
/Title(Enscript Output)
/Author()
/Creator(GNU Enscript 1.6.6)>>endobj
xref
0 14
0000000000 65535 f 
0000000640 00000 n 
0000002508 00000 n 
0000000581 00000 n 
0000000421 00000 n 
0000000015 00000 n 
0000000402 00000 n 
0000000705 00000 n 
0000000952 00000 n 
0000000815 00000 n 
0000000746 00000 n 
0000000776 00000 n 
0000000893 00000 n 
0000001019 00000 n 
trailer
<< /Size 14 /Root 1 0 R /Info 2 0 R
/ID [<C07045F1EB9341C1A864C9DE1008A7BA><C07045F1EB9341C1A864C9DE1008A7BA>]
>>
startxref
2694
%%EOF
