INSERT ALL 
INTO bars (name, license, city, phone, addr) VALUES ('A.P. Stump''s','MA12347','Boston',NULL,NULL)
INTO bars (name, license, city, phone, addr) VALUES ('Blue Angel','CA45678','San Francisco',NULL,NULL)
INTO bars (name, license, city, phone, addr) VALUES ('Blue Tattoo','CA45678','San Francisco','415-567-1289','1500 Market St.')
INTO bars (name, license, city, phone, addr) VALUES ('Britannia Arms','MA12346','Boston','345-567-1289',NULL)
INTO bars (name, license, city, phone, addr) VALUES ('Cabana','CA45678','San Francisco',NULL,'1200 California Ave.')
INTO bars (name, license, city, phone, addr) VALUES ('Caravan','IL12345','Chicago',NULL,NULL)
INTO bars (name, license, city, phone, addr) VALUES ('Club 175','CA45678','San Francisco','415-567-1289',NULL)
INTO bars (name, license, city, phone, addr) VALUES ('Coconut Willie''s Cocktail Lounge','CA45678','San Francisco','415-567-1289',NULL)
INTO bars (name, license, city, phone, addr) VALUES ('Eulipia','IL12346','Chicago','123-456-7890','1060 West Addison')
INTO bars (name, license, city, phone, addr) VALUES ('Gecko Grill','IL12348','Chicago',NULL,'1060 West Addison')
INTO bars (name, license, city, phone, addr) VALUES ('Giza Hookah Lounge','IL12349','Chicago','345-678-9012',NULL)
INTO bars (name, license, city, phone, addr) VALUES ('Hedley Club','NY12345','New York',NULL,'161st St and River Ave')
INTO bars (name, license, city, phone, addr) VALUES ('Il Fornaio','NY12346','New York',NULL,'161st St and River Ave')
INTO bars (name, license, city, phone, addr) VALUES ('Seven Bamboo','NY12347','New York',NULL,'161st St and River Ave')
INTO bars (name, license, city, phone, addr) VALUES ('The B-Hive','MA12348','Boston','345-567-1280',NULL)
INTO bars (name, license, city, phone, addr) VALUES ('The Backbeat','CA45678','San Francisco','415-567-1289',NULL)
INTO bars (name, license, city, phone, addr) VALUES ('The Blank Club','MA12349','Boston','345-567-1281',NULL)
INTO bars (name, license, city, phone, addr) VALUES ('The Shark and Rose','MA12345','Boston',NULL,NULL)
SELECT * FROM dual;
INSERT ALL
INTO beers VALUES ('Blue Moon','Coors Brewing Company')
INTO beers VALUES ('Budweiser','Anheuser-Busch')
INTO beers VALUES ('Creamy Dark','Jacob Leinenkugel Brewing Company')
INTO beers VALUES ('Extra Gold','Coors Brewing Company')
INTO beers VALUES ('Hefeweizen','Jacob Leinenkugel Brewing Company')
INTO beers VALUES ('Hefeweizen Doppelbock','Jacob Leinenkugel Brewing Company')
INTO beers VALUES ('ICEHOUSE','Plank Road Brewery')
INTO beers VALUES ('Killian''s','Coors Brewing Company')
INTO beers VALUES ('Michelob Amber Bock','Anheuser-Busch')
INTO beers VALUES ('Michelob Golden Draft','Anheuser-Busch')
INTO beers VALUES ('Michelob Golden Draft Light','Anheuser-Busch')
INTO beers VALUES ('Michelob ULTRA','Anheuser-Busch')
INTO beers VALUES ('Original Premium','Jacob Leinenkugel Brewing Company')
INTO beers VALUES ('Original Premium Lager','Jacob Leinenkugel Brewing Company')
INTO beers VALUES ('Original Premium Lager Dog','Plank Road Brewery')
INTO beers VALUES ('Sauza Diablo','Miller Brewing Company')
INTO beers VALUES ('Southpaw Light','Plank Road Brewery')
INTO beers VALUES ('Stolichnaya Citrona','Miller Brewing Company')
INTO beers VALUES ('Zima','Coors Brewing Company')
INTO beers VALUES ('Zima Citrus','Coors Brewing Company')
SELECT * FROM dual;
INSERT ALL
INTO drinkers VALUES ('Bob','San Francisco','415-234-6789',NULL)
INTO drinkers VALUES ('Erik','San Francisco','415-234-6789',NULL)
INTO drinkers VALUES ('Herb','Boston',NULL,NULL)
INTO drinkers VALUES ('Jesse','San Francisco','415-234-6789',NULL)
INTO drinkers VALUES ('John','Chicago',NULL,'1060 West Addison')
INTO drinkers VALUES ('Justin','Boston',NULL,NULL)
INTO drinkers VALUES ('Mike','Boston',NULL,NULL)
INTO drinkers VALUES ('Rebecca','Chicago',NULL,'1060 West Addison')
INTO drinkers VALUES ('Tom','Chicago',NULL,'1060 West Addison')
INTO drinkers VALUES ('Vince','New York','234-456-7890','161st St and River Ave')
SELECT * FROM dual;
INSERT ALL
INTO frequents VALUES ('Mike','A.P. Stump''s')
INTO frequents VALUES ('Erik','Blue Angel')
INTO frequents VALUES ('Jesse','Blue Angel')
INTO frequents VALUES ('Tom','Blue Angel')
INTO frequents VALUES ('Vince','Blue Angel')
INTO frequents VALUES ('John','Caravan')
INTO frequents VALUES ('Tom','Caravan')
INTO frequents VALUES ('Bob','Coconut Willie''s Cocktail Lounge')
INTO frequents VALUES ('Rebecca','Coconut Willie''s Cocktail Lounge')
INTO frequents VALUES ('Justin','Gecko Grill')
INTO frequents VALUES ('Rebecca','Gecko Grill')
INTO frequents VALUES ('Herb','Seven Bamboo')
INTO frequents VALUES ('Vince','Seven Bamboo')
INTO frequents VALUES ('Mike','The Shark and Rose')
SELECT * FROM dual;
INSERT ALL
INTO likes VALUES ('John','Blue Moon')
INTO likes VALUES ('Mike','Blue Moon')
INTO likes VALUES ('John','Budweiser')
INTO likes VALUES ('Mike','Budweiser')
INTO likes VALUES ('John','Creamy Dark')
INTO likes VALUES ('Mike','Creamy Dark')
INTO likes VALUES ('Mike','Hefeweizen')
INTO likes VALUES ('John','Killian''s')
INTO likes VALUES ('John','Michelob Golden Draft')
INTO likes VALUES ('Mike','Michelob Golden Draft Light')
INTO likes VALUES ('John','Original Premium')
INTO likes VALUES ('Mike','Original Premium Lager')
INTO likes VALUES ('Jesse','Original Premium Lager Dog')
INTO likes VALUES ('Mike','Original Premium Lager Dog')
INTO likes VALUES ('John','Stolichnaya Citrona')
SELECT * FROM dual;
INSERT ALL
INTO sells VALUES ('A.P. Stump''s','Hefeweizen',6.00)
INTO sells VALUES ('Blue Angel','Hefeweizen Doppelbock',5.50)
INTO sells VALUES ('Blue Angel','Original Premium Lager Dog',6.25)
INTO sells VALUES ('Blue Tattoo','Killian''s',6.00)
INTO sells VALUES ('Britannia Arms','Budweiser',6.50)
INTO sells VALUES ('Cabana','Budweiser',5.00)
INTO sells VALUES ('Cabana','Hefeweizen Doppelbock',7.00)
INTO sells VALUES ('Cabana','Original Premium Lager Dog',5.00)
INTO sells VALUES ('Caravan','Budweiser',5.50)
INTO sells VALUES ('Caravan','Original Premium Lager Dog',3.50)
INTO sells VALUES ('Club 175','Budweiser',4.50)
INTO sells VALUES ('Coconut Willie''s Cocktail Lounge','Budweiser',3.25)
INTO sells VALUES ('Eulipia','Hefeweizen Doppelbock',4.50)
INTO sells VALUES ('Gecko Grill','Budweiser',3.00)
INTO sells VALUES ('Giza Hookah Lounge','Stolichnaya Citrona',6.00)
INTO sells VALUES ('Hedley Club','Hefeweizen',8.00)
INTO sells VALUES ('Seven Bamboo','Budweiser',2.50)
INTO sells VALUES ('The B-Hive','Michelob Amber Bock',5.00)
INTO sells VALUES ('The Backbeat','Killian''s',3.50)
INTO sells VALUES ('The Blank Club','Budweiser',5.50)
INTO sells VALUES ('The Shark and Rose','Budweiser',4.50)
INTO sells VALUES ('The Shark and Rose','Original Premium Lager Dog',5.50)
SELECT * FROM dual;

