#
# Makefile for Assignment 2
#
all :  grep1 grep2 sort
sort : sort.c
	gcc sort.c -o Sort

grep1: grep1.c
	gcc grep1.c -o Grep1

grep2: grep2.c
	gcc grep2.c -o Grep2

clean: 
	rm Grep1
	rm Grep2
	rm Sort
